<settings
	xmlns="http://maven.apache.org/SETTINGS/1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0                       http://maven.apache.org/xsd/settings-1.0.0.xsd">
	<servers>
		<server>
			<id>mulesoft-ee-release</id>
			<username>palantirtechnologies.nexus</username>
			<password>eIGaJGCs</password>
		</server>
		<server>
			<id>mulesoft-release</id>
			<username>palantir-admin</username>
			<password>_W45a}s]5X</password>
		</server>
		<server>
			<id>Exchange2</id>
			<username>palantir-admin</username>
			<password>_W45a}s]5X</password>
		</server>
		<server>
			<id>Artifactory</id>
			<username>finsys-publish</username>
			<password>9aXZDMMRhUoC9hFG1fOZvzhNT56s9q</password>
		</server>
	</servers>
	<profiles>
		<profile>
			<id>mule-extra-repos</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<repositories>
				<repository>
					<id>mule-public</id>
					<url>https://repository.mulesoft.org/nexus/content/repositories/public </url>
				</repository>
			</repositories>
		</profile>
		<profile>
			<id>default</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<repositories>
				<!-- MuleSoft public repositories -->
				<repository>
					<id>mulesoft-release</id>
					<url>https://repository.mulesoft.org/nexus/content/groups/public</url>
					<releases>
						<enabled>true</enabled>
					</releases>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
				</repository>
				<!-- MuleSoft EE repositories -->
				<repository>
					<id>mulesoft-ee-release</id>
					<url>https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/</url>
					<layout>default</layout>
					<releases>
						<enabled>true</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
				</repository>
				<repository>
					<releases>
						<updatePolicy>never</updatePolicy>
					</releases>
					<snapshots>
						<enabled>false</enabled>
						<updatePolicy>never</updatePolicy>
					</snapshots>
					<id>ibm-maven-repo</id>
					<name>ibm-maven-repo</name>
					<url>http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/maven/repository/</url>
				</repository>
			</repositories>
			<pluginRepositories>
				<pluginRepository>
					<id>mule-public</id>
					<url> https://repository.mulesoft.org/nexus/content/repositories/public </url>
				</pluginRepository>
				<pluginRepository>
					<id>mulesoft-release</id>
					<name>mulesoft release repository</name>
					<layout>default</layout>
					<url>https://repository.mulesoft.org/nexus/content/groups/public</url>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
				</pluginRepository>
				<pluginRepository>
					<id>mulesoft-ee-release</id>
					<url>https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/</url>
					<layout>default</layout>
					<releases>
						<enabled>true</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
				</pluginRepository>
			</pluginRepositories>
		</profile>
	</profiles>
	<pluginGroups>
		<pluginGroup>org.mule.tools</pluginGroup>
	</pluginGroups>
</settings>