#%RAML 1.0 NamedExample
bank-example:
  id: null
  name: "Bank Of America"
  institutionType: "Bank"
  bankCode: "BOFAUSV1XXX"
  headquartersCountry: "USA"
  headquartersState:  "North Carolina"
  headquartersCity: "Charlotte"
  externalIds:
  - id: null
    externalId: "5390 0754 7034"  
    externalIdType: [ "BBAN" ]
  - id: null
    externalId: "AT483200000012345864"  
    externalIdType: [ "IBAN" ]
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
