#%RAML 1.0 NamedExample
blockchain-account-example:
  id: null
  name: "My Ripple Wallet"
  accountNumber: "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn"
  accountType: "BlockchainAccount"
  primaryAccountOwner: "b7c4eddf-9c67-11eb-b4c8-0233bdd64096"
  accountStatus: "OPEN"
  accountCurrency: "USD"
  openedDate: "2020-03-15"
  blockchainAccountType: "RIPPLE"
  initialTransactionId: "0D5FB50FA65C9FE1538FD7E398FFFE9D1908DFA4576D8D7A020040686F93C77D"
