#%RAML 1.0 NamedExample
card-example:
  id: null
  name: "Bank Card"
  cardType: "Card"
  cardNumber: "1111111111111111"
  cardholderName: "Anonymous Guest"
  cardOwnerId: "f27abff9-0b00-47d6-a035-5d59470ec044"
  cardPin: "9999"
  cardStatus: "ACTIVE"
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
