#%RAML 1.0 NamedExample
creditcard-example:
  id: null
  name: "Joint VISA"
  cardType: "CreditCard"
  creditCardType: "VISA"
  cardNumber: "4514111111111111"
  cardholderName: "Joyce Witherspoon"
  cardOwnerId: "f27abff9-0b00-47d6-a035-5d59470ec044"
  accountIds: [ "6b7d64c6-8d5f-11eb-b4c8-0233bdd64096" ]
  maskedNumber: "451411******1111"
  numberLastDigits: "1111"
  cardPin: "9999"
  cardToken: "999999"
  cardSecurityCode: "555"
  cardStatus: "ACTIVE"
  expiryMonth: 11
  expiryYear: 2021
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
