#%RAML 1.0 NamedExample
credit-transaction-example:
  id: null
  name: "T-000000016"
  description: "Credit Card Purchase"
  creditAccountId: "20468f5c-bb1e-4b15-a22e-cd2e660fd076"
  transactionNumber: 40000341
  transactionAmount: 15.00
  transactionType: "CreditTransaction"
  transactionSubType: "CHECK"
  transactionStatus: "CANCELLED"
  transactionDate: "2020-03-15"
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
