#%RAML 1.0 NamedExample
debit-card-example:
  id: null
  name: "Karen Debit Card"
  cardType: "DebitCard"
  cardNumber: "4519111111111111"
  cardholderName: "Karen Anne Jay"
  cardOwnerId: "f27abff9-0b00-47d6-a035-5d59470ec044"
  accountIds: [ "6b7d64c6-8d5f-11eb-b4c8-0233bdd64096" ]
  cardOwnershipType: "PRIMARY"
  cardPin: "9999"
  cardStatus: "ACTIVE"
  cardControls:
    - ATM
    - POS
  dailyPurchaseLimit: 1000.00
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
