#%RAML 1.0 NamedExample
deposit-account-example:
  id: null
  name: "Martin's Checking Account"
  routingNumber: "52000"
  accountNumber: "00007605"
  accountType: "DepositAccount"
  depositAccountType: "CHECKING"
  primaryAccountOwner: "b7c4eddf-9c67-11eb-b4c8-0233bdd64096"
  accountStatus: "OPEN"
  accountBalance: 102.70
  availableBalance: 2.70
  accountCurrency: "USD"
  accountLabel: "Checking"
  interestRate: 0.05
  taxIdentificationNumber: "012345678"
  openedDate: "2020-03-15"
  overdraftLimit: 0.0
  lastDepositDate: "2021-09-01"
  lastWithdrawalDate: "2021-09-17"
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
