#%RAML 1.0 NamedExample
document-example:
  id: null
  documentStatus: "CURRENT"
  signatureStatus: "UNSIGNED"
  externalIds:
  - id: null
    externalId: "2d37e973-3834-4343-984f-c2820f34bf63"
    externalIdType: [ "LOS" ]
    status: "VALID"
    statusLastChangedDate: "2021-06-25T21:40:46.000Z"
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
  