#%RAML 1.0 NamedExample
general-ledger-account-example:
  id: null
  name: "PAYMENTS"
  accountNumber: "5000"
  accountType: "GeneralLedgerAccount"
  primaryAccountOwner: "b7c4eddf-9c67-11eb-b4c8-0233bdd64096"
  accountStatus: "OPEN"
  accountCurrency: "USD"
  openedDate: "2021-01-05"
  glAccountType: "CLEARING"
