#%RAML 1.0 NamedExample
institution-example:
  id: null
  name: "Bank Of America"
  institutionType: "Bank"
  bankCode: "BOFAUS3N"
  headquartersCountry: "US"
  headquartersRegion: "North Carolina"
  headquartersCity: "Charlotte"
