#%RAML 1.0 NamedExample
loan-account-example:
  id: null
  name: "Martin's Line of Credit"
  accountNumber: "00007604"
  accountType: "LoanAccount"
  primaryAccountOwner: "b7c4eddf-9c67-11eb-b4c8-0233bdd64096"
  accountStatus: "OPEN"
  accountBalance: 0.0
  availableBalance: 10000.00
  accountCurrency: "CAD"
  accountLabel: "Primary"
  interestRate: 7.5
  taxIdentificationNumber: "012345678"
  openedDate: "2020-03-15"
  loanType: "VEHICLE"
  creditLimit: 10000.00
  originalLoanAmount: 50000.00
  minimumPayment: 1000.00
  principalBalance: 25000.00
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
