#%RAML 1.0 NamedExample
loan-document-example:
  id: "4245f35a-ca68-4082-b9d8-133a536c8ac6"
  documentStatus: "CURRENT"
  signatureStatus: "UNSIGNED"
  loanApplication: "450aa90a-f854-4e5f-baa1-6fee062f8c7e"
  externalIds:
  - id: null
    externalId: "2d37e973-3834-4343-984f-c2820f34bf63"
    externalIdType: [ "DOCUSIGN" ]
    status: "VALID"
    statusLastChangedDate: "2021-06-25T21:40:46.000Z"
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
  