#%RAML 1.0 NamedExample
loan-application-example:
  id: "450aa90a-f854-4e5f-baa1-6fee062f8c7e"
  applicationType: "INDIVIDUAL"
  loanPurpose: "VEHICLE"
  timeAtAddressMonths: 67
  customers:
  - id: null
    partyRoleType: "Customer"
    customerStatus: "ACTIVE"
    party:
    - id: null
      partyType: "Individual"
      personName: "Loan User1"
  housingStatus: "OWN"
  taxIdentificationNumber: "999-99-9999"
  driversLicenseLastDigits: "1234"
  requestedLoanAmount: 35000
  loanDurationMonths: 36
  citizenship: "US"
  employmentStatus: "EMPLOYED"
  hasAdditionalIncome: true
  additionalIncomeAmount: 12000
  additionalIncomeSource: "BONUS"
  monthlyHousingCostsAmount: 1000
  estimatedHomeEquityAmount: 80000
  totalLiquidAssetsAmount: 60000
  totalRetirementAssetsAmount: 300000
  loanApplicationStatus: "BOOKED"
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
  