#%RAML 1.0 NamedExample
payment-execution-request-example:
  Amount: 333.33
  CreditorBank: "BOFAUS3N"
  CreditorBankCountry: "US"
  CreditorAccountType: "SavingsSpecial"
  CreditorAcountCurrency: "USD"
  DebtorBank: "ROYCCAT2IBO"
  DebtorBankCountry: "CA"
  DebtorAccountType: "SavingsSpecial"
  DebtorAcountCurrency: "CAD"
  TransferType: "INTERNATIONAL_TRANSFER"
  ChannelType: "Bank_SWIFT"
  Stage: "OB_EXPERIENCE"
