#%RAML 1.0 NamedExample
transfer-transaction-example:
  id: null
  name: "T-000000016"
  description: "Credit Card Purchase"
  debitAccountId: "1b0b27c2-5328-460a-ad62-fbf908e8d3a8"
  creditAccountId: "20468f5c-bb1e-4b15-a22e-cd2e660fd076"
  transactionNumber: null
  transactionAmount: 106.50
  transactionType: "TransferTransaction"
  transactionSubType: "ATM"
  transactionStatus: "POSTED"
  transactionDate: "2020-03-15"
  postedDate: "2020-03-18"
  vendorName: "A&M Records"
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
