#%RAML 1.0 NamedExample
transaction-example:
  id: null
  name: "T-000000016"
  description: "Credit Card Purchase"
  transactionNumber: 39732845
  transactionAmount: 15.00
  transactionType: "DebitTransaction"
  transactionSubType: "ATM"
  transactionStatus: "POSTED"
  transactionDate: "2020-03-15"
  postedDate: "2020-03-15"
  vendorName: "A&M Records"
  isDisputed: true
  disputedReason: "FRAUD"
  notes: "Transaction processed"
  auditInfo:
    createdDate: "2020-03-15T15:03:01Z"
    createdBy: "system"
    updatedDate: "2020-03-15T15:03:01Z"
    updatedBy: "system"
    isDeleted: false
